In [139]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
df = pd.read_csv(Path('__file__').resolve().parents[3] / "resources" / "data.csv")

- roll_mean_10d: Close price rolling mean for 10 days
- roll_mean_20d: Close price rolling mean for 20 days
- growing_moving_average: if mean price for 10 days more than mean price for 20 days (1 if roll_mean_10d > roll_mean_20d 1, else 0)
- high_minus_low_relative: (High price for day - Low price) / Close price
- growth_{days}d, days=[1,3,7,30,90,252,365]: how much growth price since X day to today (Close price / Close price for previous X day)
- volatility: std for 30 days for (Close price / Close price for previous day) * sqrt 252 trading days in a year (growth_1d.rolling(30).std() * np.sqrt(252))
- sharpe: (growth_252d - RISK_FREE_RATE=0.045) / volatility
- RSI: Relative Strength Index (smoothed measure of recent gains vs. recent losses over the specified period)
- ADX: Average Directional Index, measures trend strength (0–20 → Weak/No trend; 20–40 → Developing/Moderate trend; 40–60 → Strong trend; 60+ → Very strong trend.)
- +DI: Positive Directional Indicator (high → strong upward trend; low → weak upward trend (or possibly downward trend))
- -DI: Negative Directional Movement (high → strong downward trend; low → weak downward trend (or possibly upward trend))
- MACD: Moving Average Convergence Divergence
- MACD_signal: MACD line crossing above Signal line → Bullish signal (momentum up); MACD line crossing below Signal line → Bearish signal (momentum down).
- MACD_hist: momentum strength (positive = bullish, negative = bearish)
- CCI: Commodity Channel Index (CCI > +100 → Strong bullish signal (overbought / upward momentum); CCI < -100 → Strong bearish signal (oversold / downward momentum); Crossing ±100 → Often used as entry/exit signals.)
- CMO: Chande Momentum Oscillator ([-100, +100]: CMO > +50 → Strong bullish momentum; CMO < -50 → Strong bearish momentum; CMO crossing above 0 → Possible start of an uptrend; CMO crossing below 0 → Possible start of a downtrend.)
- TRIX: Triple-smoothed exponential moving average of the price (Positive → uptrend gaining strength; Negative → downtrend gaining strength)
- ULTOSC: Ultimate Oscillator, capture momentum across three different timeframes to reduce false signals (overbought (>70) and oversold (<30) conditions)
- OBV: On-Balance Volume, relates price movement to volume (A rising OBV: volume is heavier on up days → potential buying pressure; A falling OBV: volume is heavier on down days → potential selling pressure.)
- AD: Accumulation/Distribution (A/D) Line, detect whether a stock is being accumulated or distributed, even if the price itself isn’t moving much (Rising A/D → accumulation (buying pressure), Falling A/D → distribution (selling pressure).)
- ADOSC: Accumulation/Distribution Oscillator, measures the momentum of accumulation/distribution using volume and price (Positive values → buying pressure (accumulation increasing); Negative values → selling pressure (distribution increasing); Crossovers of zero or the signal line: potential trend changes)
- ATR: Average True Range, how much the price typically moves in a given period, accounting for gaps and intraday swings (Higher ATR → higher price volatility; Lower ATR → lower price volatility)
- NATR: Normalized Average True Range, how volatile an asset is relative to its price (typical price movement over the period is about X% of the closing price.)
- AvgPrice: Average price of a candlestick (or bar) for each period
- MedPrice: Median price of a candlestick (or bar) for each period
- TypPrice: Typical price for a given period
- WCLPrice: Weighted close price for a given period
- Doji: Doji candlestick patterns, where the open and close prices are almost equal.
- Engulfing: Engulfing candlestick patterns (1 → Bullish Engulfing, -1 → Bearish Engulfing, 0 → No Engulfing pattern)
- Hammer: Hammer candlestick patterns (1 if hammer pattern detected: (Lower shadow at least twice the body → long lower wick. Body is ≤ 30% of total candle range → small real body.) 0 otherwise)
- ShootingStar: Shooting Star candlestick patterns (1 if a Shooting Star is detected: (Upper shadow at least twice the body → long upper wick. Body ≤ 30% of total candle range → small real body.) 0 otherwise.)
- Momentum: Measure of price change speed or trend (difference between the current value and the value period steps ago)
- ROC: Rate of Change
- ROCP: Rate of Change in proportion
- ROCR: Rate of Change Ratio, relative change expressed as a ratio (1 → no change over the period; Greater than 1 → the series increased over the period; Less than 1 → the series decreased over the period.)
- ROCR100: Rate of Change Ratio expressed as a percentage
- WilliamsR: Williams Percent Range, measures overbought and oversold levels ([0, -100]: Above -20 → asset may be overbought; Below -80 → asset may be oversold; It compares the current close to the recent high-low range, giving a sense of momentum and reversal potential.)
- ADXR: Average Directional Movement Rating, measures trend strength with a bit of "lag" to reduce noise. often used to filter out false signals in choppy markets.
- APO: Absolute Price Oscillator (APO > 0 → Upward momentum (short EMA above long EMA). APO < 0 → Downward momentum (short EMA below long EMA). Crossing zero → Possible trend reversal signal.)
- PPO: Percentage Price Oscillator (PPO > 0 → Short-term EMA is above long-term EMA → bullish momentum; PPO < 0 → Short-term EMA is below long-term EMA → bearish momentum; Crossing zero line → Potential trend reversal.)
- StochK: Stochastic Oscillator ([0, 100]: %K or %D > 80 → Overbought (possible reversal down); %K or %D < 20 → Oversold (possible reversal up)
- StochD: %K crossing above %D → Bullish signal; %K crossing below %D → Bearish signal.
- StochFastK: Stochastic Oscillator 
- StochFastD: Stochastic Oscillator 
- StochRSI_K: Stochastic RSI ([0, 1]: > 0.8 → Overbought, < 0.2 → Oversold.)
- StochRSI_D: Stochastic RSI ([0, 1]: > 0.8 → Overbought, < 0.2 → Oversold.)
- gdppot_us_yoy: Real Potential Gross Domestic Product yearly growth
- gdppot_us_qoq: Real Potential Gross Domestic Product quaterly growth
- cpi_core_yoy: Core CPI index yearly growth
- cpi_core_mom: Core CPI index montly growth
- growth_FEDFUNDS_Xd, X=[1,3,7,30,90,252,365]: Fed rate growth
- growth_DGS1_Xd: DGS1 growth
- growth_DGS5_Xd: DGS5 growth
- growth_DGS10_Xd: DGS10 growth
- spx_dod: S&P500 daily growth
- spx_qoq: S&P500 quaterly growth
- spx_yoy: S&P500 yearly growth
- growth_^GDAXI_Xd: 40 largest German companies growth
- growth_^GSPC_Xd: SNP Real Time Price
- growth_^DJI_Xd: Dow Jones Industrial Average - 30 large, publicly owned blue-chip companies trading on the New York Stock Exchange (NYSE) and Nasdaq
- growth_VOO_Xd: VOO
- growth_EPI_Xd: WisdomTree India Earnings Fund
- growth_^VIX_Xd: Volatility Index
- growth_GC=F_Xd: GOLD
- growth_CL=F_Xd: WTI Crude Oil
- growth_BZ=F_Xd: Brent Oil
- growth_BTC-USD_Xd: BTC-USD

In [3]:
df['Date'].min(), df['Date'].max()

('2010-01-04', '2025-07-31')

In [130]:
columns = ['roll_mean_10d', 'roll_mean_20d','growing_moving_average', 'high_minus_low_relative', 
           'growth_1d','growth_3d','growth_7d','growth_30d','growth_90d','growth_252d','growth_365d','volatility','sharpe',
           'RSI','ADX','+DI','-DI','MACD','MACD_signal','MACD_hist','CCI','CMO','TRIX','ULTOSC','OBV','AD','ADOSC','ATR','NATR',
           'AvgPrice','MedPrice','TypPrice','WCLPrice','Doji','Engulfing','Hammer','ShootingStar','Momentum','ROC','ROCP','ROCR','ROCR100',
           'WilliamsR','ADXR','APO','PPO','StochK','StochD','StochFastK','StochFastD','StochRSI_K','StochRSI_D','year','month','weekday',
           'gdppot_us_yoy','gdppot_us_qoq','cpi_core_yoy','cpi_core_mom','fedfunds_yoy','fedfunds_mom',
           'growth_DGS1_1d','growth_DGS1_3d','growth_DGS1_7d','growth_DGS1_30d','growth_DGS1_90d','growth_DGS1_252d','growth_DGS1_365d',
           'growth_DGS5_1d','growth_DGS5_3d','growth_DGS5_7d','growth_DGS5_30d','growth_DGS5_90d','growth_DGS5_252d','growth_DGS5_365d',
           'growth_DGS10_1d','growth_DGS10_3d','growth_DGS10_7d','growth_DGS10_30d','growth_DGS10_90d','growth_DGS10_252d','growth_DGS10_365d',
           'spx_dod','spx_qoq','spx_yoy',
           'growth_^GDAXI_1d','growth_^GDAXI_7d','growth_^GDAXI_30d','growth_^GDAXI_90d','growth_^GDAXI_252d','growth_^GDAXI_365d',
           'growth_^GSPC_1d','growth_^GSPC_7d','growth_^GSPC_30d','growth_^GSPC_90d','growth_^GSPC_252d','growth_^GSPC_365d',        
           'growth_^DJI_1d','growth_^DJI_3d','growth_^DJI_7d','growth_^DJI_30d','growth_^DJI_90d','growth_^DJI_252d','growth_^DJI_365d',
           'growth_VOO_1d','growth_VOO_3d','growth_VOO_7d','growth_VOO_30d','growth_VOO_90d','growth_VOO_252d','growth_VOO_365d',
           'growth_EPI_1d','growth_EPI_3d','growth_EPI_7d','growth_EPI_30d','growth_EPI_90d','growth_EPI_252d','growth_EPI_365d',
           'growth_^VIX_1d','growth_^VIX_3d','growth_^VIX_7d','growth_^VIX_30d','growth_^VIX_90d','growth_^VIX_252d','growth_^VIX_365d',
           'growth_GC=F_1d','growth_GC=F_3d','growth_GC=F_7d','growth_GC=F_30d','growth_GC=F_90d','growth_GC=F_252d','growth_GC=F_365d',
           'growth_CL=F_1d','growth_CL=F_3d','growth_CL=F_7d','growth_CL=F_30d','growth_CL=F_90d','growth_CL=F_252d','growth_CL=F_365d',
           'growth_BZ=F_1d','growth_BZ=F_3d','growth_BZ=F_7d','growth_BZ=F_30d','growth_BZ=F_90d','growth_BZ=F_252d','growth_BZ=F_365d',
           'growth_BTC-USD_1d','growth_BTC-USD_3d','growth_BTC-USD_7d','growth_BTC-USD_30d','growth_BTC-USD_90d','growth_BTC-USD_252d','growth_BTC-USD_365d']

numeric = ['roll_mean_10d', 'roll_mean_20d','high_minus_low_relative',
           'growth_1d','growth_3d','growth_7d','growth_30d','growth_90d','growth_252d','growth_365d','volatility','sharpe',
           'RSI','ADX','+DI','-DI','MACD','MACD_signal','MACD_hist','CCI','CMO','TRIX','ULTOSC','OBV','AD','ADOSC','ATR','NATR',
           'AvgPrice','MedPrice','TypPrice','WCLPrice','Momentum','ROC','ROCP','ROCR','ROCR100',
           'WilliamsR','ADXR','APO','PPO','StochK','StochD','StochFastK','StochFastD','StochRSI_K','StochRSI_D',
           'gdppot_us_yoy','gdppot_us_qoq','cpi_core_yoy','cpi_core_mom','fedfunds_yoy','fedfunds_mom',
           'growth_DGS1_1d','growth_DGS1_3d','growth_DGS1_7d','growth_DGS1_30d','growth_DGS1_90d','growth_DGS1_252d','growth_DGS1_365d',
           'growth_DGS5_1d','growth_DGS5_3d','growth_DGS5_7d','growth_DGS5_30d','growth_DGS5_90d','growth_DGS5_252d','growth_DGS5_365d',
           'growth_DGS10_1d','growth_DGS10_3d','growth_DGS10_7d','growth_DGS10_30d','growth_DGS10_90d','growth_DGS10_252d','growth_DGS10_365d',
           'spx_dod','spx_qoq','spx_yoy',
           'growth_^GDAXI_1d','growth_^GDAXI_7d','growth_^GDAXI_30d','growth_^GDAXI_90d','growth_^GDAXI_252d','growth_^GDAXI_365d',
           'growth_^GSPC_1d','growth_^GSPC_7d','growth_^GSPC_30d','growth_^GSPC_90d','growth_^GSPC_252d','growth_^GSPC_365d',
           'growth_^DJI_1d','growth_^DJI_3d','growth_^DJI_7d','growth_^DJI_30d','growth_^DJI_90d','growth_^DJI_252d','growth_^DJI_365d',
           'growth_VOO_1d','growth_VOO_3d','growth_VOO_7d','growth_VOO_30d','growth_VOO_90d','growth_VOO_252d','growth_VOO_365d',
           'growth_EPI_1d','growth_EPI_3d','growth_EPI_7d','growth_EPI_30d','growth_EPI_90d','growth_EPI_252d','growth_EPI_365d',
           'growth_^VIX_1d','growth_^VIX_3d','growth_^VIX_7d','growth_^VIX_30d','growth_^VIX_90d','growth_^VIX_252d','growth_^VIX_365d',
           'growth_GC=F_1d','growth_GC=F_3d','growth_GC=F_7d','growth_GC=F_30d','growth_GC=F_90d','growth_GC=F_252d','growth_GC=F_365d',
           'growth_CL=F_1d','growth_CL=F_3d','growth_CL=F_7d','growth_CL=F_30d','growth_CL=F_90d','growth_CL=F_252d','growth_CL=F_365d',
           'growth_BZ=F_1d','growth_BZ=F_3d','growth_BZ=F_7d','growth_BZ=F_30d','growth_BZ=F_90d','growth_BZ=F_252d','growth_BZ=F_365d',
           'growth_BTC-USD_1d','growth_BTC-USD_3d','growth_BTC-USD_7d','growth_BTC-USD_30d','growth_BTC-USD_90d','growth_BTC-USD_252d','growth_BTC-USD_365d']

binary = ['growing_moving_average','Doji','Hammer','ShootingStar']
categorical = ['Engulfing','year','month','weekday',]
idx = ['Date','ticker']

to_predict_numerical = ['growth_future_1d','growth_future_3d','growth_future_7d','growth_future_30d','growth_future_90d','growth_future_252d','growth_future_365d']
to_predict_binary = ['is_positive_growth_1d_future','is_positive_growth_3d_future','is_positive_growth_7d_future','is_positive_growth_30d_future',
                     'is_positive_growth_90d_future','is_positive_growth_252d_future','is_positive_growth_365d_future',]

In [131]:
assert len(numeric) + len(binary) + len(categorical) == len(columns)

In [11]:
print(f'Total features size: {len(columns)}')
print(f'Total predict size: {len(to_predict_numerical)}')

Total features size: 153
Total predict size: 7

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1101534 entries, 0 to 1101533
Columns: 180 entries, Date to growth_BTC-USD_365d
dtypes: float64(163), int64(15), object(2)
memory usage: 1.5+ GB

In [13]:
nans = df[columns].isna().sum()
nans[nans != 0].sort_values().tail(20)

growth_CL=F_365d        97034
growth_GC=F_365d        97315
growth_BZ=F_365d       105648
growth_365d            109080
growth_VOO_252d        112231
growth_^GDAXI_365d     113197
growth_DGS10_252d      113660
growth_DGS1_252d       113660
growth_DGS5_252d       113660
growth_DGS10_365d      141338
growth_DGS1_365d       141338
growth_DGS5_365d       141338
growth_VOO_365d        142410
growth_BTC-USD_1d      317829
growth_BTC-USD_3d      318373
growth_BTC-USD_7d      318919
growth_BTC-USD_30d     323560
growth_BTC-USD_90d     334753
growth_BTC-USD_252d    364822
growth_BTC-USD_365d    386468
dtype: int64

### EDA

##### Correlations
drop highly corr features with each other

In [118]:
columns = ['growing_moving_average', 'high_minus_low_relative', 
           'growth_1d','growth_3d','growth_7d','growth_30d','growth_90d','growth_252d','growth_365d','volatility','sharpe',
           'RSI','ADX','+DI','-DI','MACD_signal','MACD_hist','CCI','TRIX','ULTOSC','OBV','ADOSC','ATR','NATR',
           'AvgPrice','Doji','Engulfing','Hammer','ShootingStar','Momentum','ROC',
           'ADXR','StochFastK','StochFastD','StochRSI_K','year','month','weekday',
           'gdppot_us_qoq','cpi_core_yoy','cpi_core_mom','fedfunds_yoy','fedfunds_mom',
           'growth_DGS1_1d','growth_DGS1_3d','growth_DGS1_7d','growth_DGS1_30d','growth_DGS1_90d','growth_DGS1_252d',
           'growth_DGS5_1d','growth_DGS5_3d','growth_DGS5_7d','growth_DGS5_30d','growth_DGS5_90d','growth_DGS5_252d','growth_DGS5_365d','spx_qoq',
           'growth_^GDAXI_1d','growth_^GDAXI_7d','growth_^GDAXI_30d','growth_^GDAXI_90d','growth_^GDAXI_252d','growth_^GDAXI_365d',
           'growth_^GSPC_1d','growth_^GSPC_7d','growth_^GSPC_30d','growth_^GSPC_90d','growth_^GSPC_252d','growth_^GSPC_365d',        
           'growth_EPI_1d','growth_EPI_3d','growth_EPI_7d','growth_EPI_30d','growth_EPI_90d','growth_EPI_252d','growth_EPI_365d',
           'growth_^VIX_1d','growth_^VIX_3d','growth_^VIX_7d','growth_^VIX_30d','growth_^VIX_90d','growth_^VIX_252d','growth_^VIX_365d',
           'growth_GC=F_1d','growth_GC=F_3d','growth_GC=F_7d','growth_GC=F_30d','growth_GC=F_90d','growth_GC=F_252d','growth_GC=F_365d',
           'growth_CL=F_1d','growth_CL=F_3d','growth_CL=F_7d','growth_CL=F_30d','growth_CL=F_90d','growth_CL=F_252d','growth_CL=F_365d',
           'growth_BZ=F_1d','growth_BZ=F_3d','growth_BZ=F_7d','growth_BZ=F_30d','growth_BZ=F_90d','growth_BZ=F_252d','growth_BZ=F_365d',
           'growth_BTC-USD_1d','growth_BTC-USD_3d','growth_BTC-USD_7d','growth_BTC-USD_30d','growth_BTC-USD_90d','growth_BTC-USD_252d','growth_BTC-USD_365d',
          # 'roll_mean_20d', 'StochD', 'StochK', 'WilliamsR','CMO','MACD','roll_mean_10d', 'MedPrice','TypPrice','WCLPrice','APO','AD','ROCP','ROCR',
          # 'ROCR100','PPO','StochRSI_D','gdppot_us_yoy','growth_DGS1_365d','growth_DGS10_252d','growth_DGS10_1d','growth_DGS10_3d','growth_DGS10_7d',
          # 'growth_VOO_1d','growth_VOO_3d','growth_VOO_7d','growth_VOO_30d','growth_VOO_90d','growth_VOO_252d','growth_VOO_365d',
          # 'growth_DGS10_30d','growth_DGS10_90d','growth_DGS10_365d','spx_dod','spx_yoy',
          # 'growth_^DJI_1d','growth_^DJI_3d','growth_^DJI_7d','growth_^DJI_30d','growth_^DJI_90d','growth_^DJI_252d','growth_^DJI_365d',
          ]

corr_feats = df[columns + to_predict_numerical + to_predict_binary].corr()

In [119]:
feat = 'growth_BTC-USD_1d'
corr_feats[abs(corr_feats[feat]) > 0.8][feat]

growth_BTC-USD_1d    1.0
Name: growth_BTC-USD_1d, dtype: float64

In [129]:
corr_feats[abs(corr_feats['growth_future_30d']) > 0.1]['growth_future_30d']

high_minus_low_relative           0.114904
volatility                        0.145502
NATR                              0.162004
fedfunds_mom                     -0.114807
spx_qoq                          -0.112097
growth_^GSPC_90d                 -0.103833
growth_^VIX_90d                   0.131406
growth_^VIX_252d                  0.145263
growth_^VIX_365d                  0.124459
growth_future_1d                  0.183173
growth_future_3d                  0.315753
growth_future_7d                  0.477677
growth_future_30d                 1.000000
growth_future_90d                 0.570099
growth_future_252d                0.356038
growth_future_365d                0.294143
is_positive_growth_1d_future      0.111688
is_positive_growth_3d_future      0.201519
is_positive_growth_7d_future      0.314131
is_positive_growth_30d_future     0.691701
is_positive_growth_90d_future     0.371936
is_positive_growth_252d_future    0.204618
is_positive_growth_365d_future    0.160993
Name: growth_future_30d, dtype: float64

##### dummies

In [137]:
categorical

['Engulfing', 'year', 'month', 'weekday']

In [141]:
df['bullish_engulfing'] = np.where(df['Engulfing'] == -1, 1, 0)
df['bearish_engulfing'] = np.where(df['Engulfing'] == 1, 1, 0)

In [147]:
for feat in ['year', 'month', 'weekday']:
    df = df.join(pd.get_dummies(df[feat], prefix=feat).astype(int))
    df.drop(feat, axis=1, inplace=True)

In [149]:
df.head()

,Date,Close,High,Low,Open,Volume,prev_close_price,ticker,growth_1d,growth_3d,...,month_8,month_9,month_10,month_11,month_12,weekday_0,weekday_1,weekday_2,weekday_3,weekday_4
0,2010-01-04,30.109993,30.446071,30.041404,30.411778,6109400.0,NaN,MDT,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
1,2010-01-05,30.727285,30.734146,30.007115,30.178584,6568600.0,30.109993,MDT,1.020501,NaN,...,0,0,0,0,0,0,1,0,0,0
2,2010-01-06,31.233728,31.323300,30.606709,30.792747,7470700.0,30.727285,MDT,1.016482,NaN,...,0,0,0,0,0,0,0,1,0,0
3,2010-01-07,31.523119,31.564462,31.020127,31.247506,6895200.0,31.233728,MDT,1.009265,1.046932,...,0,0,0,0,0,0,0,0,1,0
4,2010-01-08,31.688486,31.757388,31.316409,31.447324,4947200.0,31.523119,MDT,1.005246,1.031282,...,0,0,0,0,0,0,0,0,0,1

##### final dataset

In [162]:
binary = ['growing_moving_average','Doji','Hammer','ShootingStar','bullish_engulfing','bearish_engulfing',
          'year_2010','year_2011','year_2012','year_2013','year_2014','year_2015','year_2016','year_2017','year_2018',
          'year_2019','year_2020','year_2021','year_2022','year_2023','year_2024','year_2025',
          'month_1','month_2','month_3','month_4','month_5','month_6','month_7','month_8','month_9','month_10','month_11','month_12',
          'weekday_0','weekday_1','weekday_2','weekday_3','weekday_4']

numeric = ['high_minus_low_relative', 
           'growth_1d','growth_3d','growth_7d','growth_30d','growth_90d','growth_252d','growth_365d','volatility','sharpe',
           'RSI','ADX','+DI','-DI','MACD_signal','MACD_hist','CCI','TRIX','ULTOSC','OBV','ADOSC','ATR','NATR',
           'AvgPrice','Momentum','ROC',
           'ADXR','StochFastK','StochFastD','StochRSI_K',
           'gdppot_us_qoq','cpi_core_yoy','cpi_core_mom','fedfunds_yoy','fedfunds_mom',
           'growth_DGS1_1d','growth_DGS1_3d','growth_DGS1_7d','growth_DGS1_30d','growth_DGS1_90d','growth_DGS1_252d',
           'growth_DGS5_1d','growth_DGS5_3d','growth_DGS5_7d','growth_DGS5_30d','growth_DGS5_90d','growth_DGS5_252d','growth_DGS5_365d','spx_qoq',
           'growth_^GDAXI_1d','growth_^GDAXI_7d','growth_^GDAXI_30d','growth_^GDAXI_90d','growth_^GDAXI_252d','growth_^GDAXI_365d',
           'growth_^GSPC_1d','growth_^GSPC_7d','growth_^GSPC_30d','growth_^GSPC_90d','growth_^GSPC_252d','growth_^GSPC_365d',        
           'growth_EPI_1d','growth_EPI_3d','growth_EPI_7d','growth_EPI_30d','growth_EPI_90d','growth_EPI_252d','growth_EPI_365d',
           'growth_^VIX_1d','growth_^VIX_3d','growth_^VIX_7d','growth_^VIX_30d','growth_^VIX_90d','growth_^VIX_252d','growth_^VIX_365d',
           'growth_GC=F_1d','growth_GC=F_3d','growth_GC=F_7d','growth_GC=F_30d','growth_GC=F_90d','growth_GC=F_252d','growth_GC=F_365d',
           'growth_CL=F_1d','growth_CL=F_3d','growth_CL=F_7d','growth_CL=F_30d','growth_CL=F_90d','growth_CL=F_252d','growth_CL=F_365d',
           'growth_BZ=F_1d','growth_BZ=F_3d','growth_BZ=F_7d','growth_BZ=F_30d','growth_BZ=F_90d','growth_BZ=F_252d','growth_BZ=F_365d',
           'growth_BTC-USD_1d','growth_BTC-USD_3d','growth_BTC-USD_7d','growth_BTC-USD_30d','growth_BTC-USD_90d','growth_BTC-USD_252d','growth_BTC-USD_365d',
          ]

idx = ['Date','ticker']

to_predict_numerical = ['growth_future_30d']
to_predict_binary = ['is_positive_growth_30d_future']

In [165]:
df[idx + numeric + binary + to_predict_numerical + to_predict_binary].head()

,Date,ticker,high_minus_low_relative,growth_1d,growth_3d,growth_7d,growth_30d,growth_90d,growth_252d,growth_365d,...,month_10,month_11,month_12,weekday_0,weekday_1,weekday_2,weekday_3,weekday_4,growth_future_30d,is_positive_growth_30d_future
0,2010-01-04,MDT,0.013440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,1,0,0,0,0,0.994757,0
1,2010-01-05,MDT,0.023661,1.020501,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0.982397,0
2,2010-01-06,MDT,0.022943,1.016482,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,1,0,0,0.964042,0
3,2010-01-07,MDT,0.017268,1.009265,1.046932,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0.954318,0
4,2010-01-08,MDT,0.013916,1.005246,1.031282,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,1,0.932159,0

In [164]:
len(binary), len(numeric)

(39, 103)

### Model

In [182]:
df = df[~df['growth_future_30d'].isna()]

In [186]:
df.reset_index(drop=True, inplace=True)

##### Data split

In [189]:
# test data: 2024-01-01 - 2025-01-08
test_data = df[df['Date'] >= '2024-01-01']
not_test_data = df[df['Date'] < '2024-01-01']

In [260]:
splits = {}
start_year = 2010
end_year = 2024  # last validation year
step = 3 # how many years add with new train set

for i, val_year in enumerate(range(2012, end_year + 1, step), start=1):
    train_start = f"{start_year}-01-01"
    train_end = f"{val_year}-01-01"
    val_start = train_end
    val_end = f"{val_year+1}-01-01"

    train_split = not_test_data[(not_test_data['Date'] >= train_start) & (not_test_data['Date'] < train_end)]
    val_split = not_test_data[(not_test_data['Date'] >= val_start) & (not_test_data['Date'] < val_end)]

    splits[f"train_{i}"] = train_split
    splits[f"val_{i}"] = val_split

In [261]:
splits.keys()

dict_keys(['train_1', 'val_1', 'train_2', 'val_2', 'train_3', 'val_3', 'train_4', 'val_4', 'train_5', 'val_5'])

In [262]:
train_1 = splits["train_1"]
val_1 = splits["val_1"]
train_2 = splits["train_2"]
val_2 = splits["val_2"]
train_3 = splits["train_3"]
val_3 = splits["val_3"]
train_4 = splits["train_4"]
val_4 = splits["val_4"]
train_5 = splits["train_5"]
val_5 = splits["val_5"]

In [250]:
feat = 'is_positive_growth_30d_future'
pd.concat([train_1[feat].value_counts(), train_1[feat].value_counts(normalize=True)], axis=1)

                               count  proportion
is_positive_growth_30d_future
1                              80265    0.600826
0                              53326    0.399174

In [251]:
pd.concat([val_1[feat].value_counts(), val_1[feat].value_counts(normalize=True)], axis=1)

                               count  proportion
is_positive_growth_30d_future
1                              42993    0.638551
0                              24336    0.361449

In [263]:
val_5

Empty DataFrame
Columns: [Date, Close, High, Low, Open, Volume, prev_close_price, ticker, growth_1d, growth_3d, growth_7d, growth_30d, growth_90d, growth_252d, growth_365d, roll_mean_10d, roll_mean_20d, growing_moving_average, high_minus_low_relative, volatility, sharpe, RSI, ADX, +DI, -DI, MACD, MACD_signal, MACD_hist, CCI, CMO, TRIX, ULTOSC, OBV, AD, ADOSC, ATR, NATR, AvgPrice, MedPrice, TypPrice, WCLPrice, Doji, Engulfing, Hammer, ShootingStar, Momentum, ROC, ROCP, ROCR, ROCR100, WilliamsR, ADXR, APO, PPO, StochK, StochD, StochFastK, StochFastD, StochRSI_K, StochRSI_D, growth_future_1d, is_positive_growth_1d_future, growth_future_3d, is_positive_growth_3d_future, growth_future_7d, is_positive_growth_7d_future, growth_future_30d, is_positive_growth_30d_future, growth_future_90d, is_positive_growth_90d_future, growth_future_252d, is_positive_growth_252d_future, growth_future_365d, is_positive_growth_365d_future, gdppot_us_yoy, gdppot_us_qoq, cpi_core_yoy, cpi_core_mom, FEDFUNDS, fedfunds_yoy, fedfunds_mom, growth_DGS1_1d, growth_DGS1_3d, growth_DGS1_7d, growth_DGS1_30d, growth_DGS1_90d, growth_DGS1_252d, growth_DGS1_365d, growth_DGS5_1d, growth_DGS5_3d, growth_DGS5_7d, growth_DGS5_30d, growth_DGS5_90d, growth_DGS5_252d, growth_DGS5_365d, growth_DGS10_1d, growth_DGS10_3d, growth_DGS10_7d, growth_DGS10_30d, growth_DGS10_90d, ...]
Index: []

[0 rows x 212 columns]